version: '3.9'
services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_DB: metaverse_magna_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local


